dist: bionic
sudo: required

# Don't build tags
if: tag IS blank

stages:
  - name: build
    if: branch =~ /^rel\// OR type = pull_request
  - name: deploy
    if: branch =~ /^rel\// AND type != pull_request

install:
  - python3.7 -m venv venv
  - export PATH=`pwd`/venv/bin:${PATH}
  - pip3.7 install mulecli

jobs:
  allow_failures:
    - name: External ARM64 Deploy
    - name: External ARM64 Integration Test
    - name: External ARM Build
    - name: External ARM Deploy
    - name: Test Release Builds
  include:
    - stage: build
      os: linux
      name: Linux AMD64 Build/Integration Test
      arch: amd64
      script:
        - scripts/travis/travis_wait.sh 90 mule build-linux-amd64
    - # same stage, parallel job
      name: Linux ARM64 Build/Integration Test
      os: linux
      arch: arm64
      script:
        - scripts/travis/travis_wait.sh 90 mule build-linux-arm64
    - # same stage, parallel job
      os: osx
      osx_image: xcode11
      arch: amd64
      name: MacOS AMD64 Build/Integration Test
      go:
        - "1.12"
      go_import_path: github.com/algorand/go-algorand
      language: go
      script:
        - ./scripts/configure_dev.sh
        - scripts/travis/travis_wait.sh 90 mule build-local

    - stage: deploy
      name: Ubuntu Deploy
      os: linux
      script:
        - scripts/travis/deploy_packages.sh
        - scripts/travis/test_release.sh
    - # same stage, parallel job
      name: MacOS Deploy
      os: osx
      osx_image: xcode11
      script: scripts/travis/deploy_packages.sh
    - # same stage, parallel job
      name: External ARM64 Deploy
      os: linux
      env:
        - BUILD_TYPE: "external_build"
        - TARGET_PLATFORM: "linux-arm64"
      addons:
        apt:
          packages:
            - awscli
      script:
        - scripts/travis/external_build.sh ./scripts/travis/deploy_packages.sh
    - # same stage, parallel job
      name: External ARM Deploy
      os: linux
      env:
        - BUILD_TYPE: "external_build"
        - TARGET_PLATFORM: "linux-arm"
      addons:
        apt:
          packages:
            - awscli
      script:
        - scripts/travis/external_build.sh ./scripts/travis/deploy_packages.sh

# Don't rebuild libsodium every time
cache:
  directories:
    - crypto/lib

before_install:
  # Disable sometimes-broken sources.list in Travis base images
  - sudo rm -vf /etc/apt/sources.list.d/*

addons:
  apt:
    packages:
      - libboost-all-dev
      - fakeroot
      - rpm
      - libssl-dev
      - libffi-dev
      - python3.7-venv
  artifacts:
    s3_region: "us-east-1"
    paths:
      - $(git ls-files -o | grep -v crypto/libsodium-fork | grep -v crypto/lib/ | grep -v ^gen/ | grep -v swagger.json.validated | tr "\n" ":")

notifications:
  slack:
    secure: lBomhenfQvDzpUGxLadga188zavtGRr05GVWI6iI8ll/uwXewij8ginQ716Axg3pJvvRMNCuTNEmg0+fVlHf0JxTG3qWG35qOUexAHGcmimPD4ugmVkufua8Oc8Nl1LRSdWvbwIKvrAU1HDA37M5tCdEOm+Sf/OL72iVWbXhlHRvhdeiKHkbkcpI/15dOH4RpXuvPeYBrgcB2Ixs7gTSVyIAU458aT0JORu7expElQ+iBP9Kqze1V4dvjJyzHTgE01z2nyAm2Xpko447y//fYX2e20iDBE5S/GukaK/TeB3pD+FoC+Z2R7Gg1qA7a/gdGFbVgP12zWmzNaKVwY1YOvx8IIwP13XutioAE7bQbnHI1zGlQ+jxk3odWKZPhZSN/YvWD3i7g/xVksaTo++zwon2UlZ7x8LmKg1kOMeA3o2TUlzjQrwZZ4cB+4HqYHEqVdsSAadaMhKK82XE1OtGImdrIX1Y/02X2F/myJXwaE4Ap8smULHWGghCL/ALad+hdyE0K4/2SYDcoaOONgX9+VgaSEtYDO00Bt4/GMcuM+gwILsfCA9ZQuxCgIFEL1QWwDud8aGU1qF20yaimDlstlLnZXsv3Oli6r/CEEUVXltI5dkJyRd/jTlqWGjFGL8agGg34EPLP24Vn4h4QcIzoMfGWXkz2yrd6i0fvMAPXds=
