tasks:
  - task: docker.Version
    configFilePath: scripts/configure_dev-deps.sh
  - task: shell.docker.Ensure
    image: algorand/go-algorand-ci-linux
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/cicd.Dockerfile
    dependencies: docker.Version
  - task: docker.Make
    image: algorand/go-algorand-ci-linux
    version: '{{ docker.Version.outputs.version }}'
    workDir: /go/src/github.com/algorand/go-algorand
    target: ci-build fulltest -j4
    dependencies: shell.docker.Ensure
  - task: shell.Make
    target: ci-deps ci-build fulltest -j4

jobs:
  build-linux-arm64:
    configs:
      arch: arm64v8
    tasks:
      - docker.Make
  build-linux-amd64:
    configs:
      arch: amd64
    tasks:
    - docker.Make
  build-linux-arm32:
    configs:
      arch: arm32v6
    tasks:
    - docker.Make
  build-local:
    tasks:
    - shell.Make
  test-ls:
    tasks:
    - shell.Shell
